<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: lldj123414
=======
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: lldj123414
>>>>>>> 755fe7b (feat/OrderUpdate)
    driver-class-name: com.mysql.cj.jdbc.Driver