spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  site:
    order-url: http://localhost:3000/orders